import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { db, events } from '@/db'

export async function POST(request: NextRequest) {
  try {
    const session = await auth()

    // Check authentication
    if (!session?.user) {
      return NextResponse.json({ message: 'Unauthorized' }, { status: 401 })
    }

    // Check role - only admin and editor can create events
    if (session.user.role === 'viewer') {
      return NextResponse.json({ message: 'Forbidden' }, { status: 403 })
    }

    const body = await request.json()

    // Validate required fields
    const requiredFields = [
      'name',
      'eventType',
      'startDate',
      'endDate',
      'region',
      'venueName',
      'candidateCapacity',
      'employerCapacity',
      'status',
      'registrationOpenDate',
      'registrationCloseDate',
    ]

    for (const field of requiredFields) {
      if (!body[field]) {
        return NextResponse.json({ message: `Missing field: ${field}` }, { status: 400 })
      }
    }

    // Create event - convert dates to ISO strings (date only, no time)
    // Note: id is auto-generated by database (UUID)
    const [newEvent] = await db
      .insert(events)
      .values({
        name: body.name,
        slug: body.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
        eventType: body.eventType,
        startDate: new Date(body.startDate).toISOString().split('T')[0],
        endDate: new Date(body.endDate).toISOString().split('T')[0],
        region: body.region,
        venueName: body.venueName,
        externalUrl: body.externalUrl || null,
        candidateCapacity: body.candidateCapacity,
        employerCapacity: body.employerCapacity,
        candidateRegistered: 0,
        employerRegistered: 0,
        status: body.status,
        registrationOpenDate: new Date(body.registrationOpenDate).toISOString().split('T')[0],
        registrationCloseDate: new Date(body.registrationCloseDate).toISOString().split('T')[0],
      })
      .returning()

    return NextResponse.json(newEvent, { status: 201 })
  } catch (error) {
    console.error('Failed to create event:', error)
    return NextResponse.json({ message: 'Internal server error' }, { status: 500 })
  }
}
