import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { db, events } from '@/db'
import { and, eq } from 'drizzle-orm'

/**
 * Helper function to extract date and time from datetime-local string
 */
function extractDateTimeComponents(datetimeStr: string) {
  const datetime = new Date(datetimeStr)
  const date = datetime.toISOString().split('T')[0]
  const time = datetime.toTimeString().split(' ')[0].substring(0, 8) // HH:MM:SS format
  return { date, time }
}

export async function POST(request: NextRequest) {
  try {
    const session = await auth()

    // Check authentication
    if (!session?.user) {
      return NextResponse.json({ message: 'Unauthorized' }, { status: 401 })
    }

    // Check role - only admin and editor can create events
    if (session.user.role === 'viewer') {
      return NextResponse.json({ message: 'Forbidden' }, { status: 403 })
    }

    const body = await request.json()

    // Validate required fields
    const requiredFields = [
      'name',
      'eventType',
      'startDate',
      'endDate',
      'region',
      'venueName',
      'candidateCapacity',
      'employerCapacity',
      'status',
      'registrationOpenDate',
      'registrationCloseDate',
    ]

    for (const field of requiredFields) {
      if (!body[field]) {
        return NextResponse.json({ message: `Missing field: ${field}` }, { status: 400 })
      }
    }

    // Extract date and time components for event start/end
    const startDateTime = extractDateTimeComponents(body.startDate)
    const endDateTime = extractDateTimeComponents(body.endDate)

    // Extract only date for registration dates (they don't have time fields in DB)
    const regOpenDate = new Date(body.registrationOpenDate).toISOString().split('T')[0]
    const regCloseDate = new Date(body.registrationCloseDate).toISOString().split('T')[0]

    // Check for existing events with the same start date and time
    const existingEvents = await db
      .select()
      .from(events)
      .where(
        and(
          eq(events.startDate, startDateTime.date),
          eq(events.startTime, startDateTime.time)
        )
      )

    if (existingEvents.length > 0) {
      return NextResponse.json(
        {
          message: `An event already exists at this date and time: ${existingEvents[0].name}`,
        },
        { status: 409 }
      )
    }

    // Create event - store both date and time
    // Note: id is auto-generated by database (UUID)
    const [newEvent] = await db
      .insert(events)
      .values({
        name: body.name,
        slug: body.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
        eventType: body.eventType,
        startDate: startDateTime.date,
        endDate: endDateTime.date,
        startTime: startDateTime.time,
        endTime: endDateTime.time,
        region: body.region,
        venueName: body.venueName,
        externalUrl: body.externalUrl || null,
        candidateCapacity: body.candidateCapacity,
        employerCapacity: body.employerCapacity,
        candidateRegistered: 0,
        employerRegistered: 0,
        status: body.status,
        registrationOpenDate: regOpenDate,
        registrationCloseDate: regCloseDate,
      })
      .returning()

    return NextResponse.json(newEvent, { status: 201 })
  } catch (error) {
    console.error('Failed to create event:', error)
    return NextResponse.json({ message: 'Internal server error' }, { status: 500 })
  }
}
