/**
 * Canonical taxonomy of industry fields/subjects
 * Maps messy source data to clean, normalized values
 */

export const canonicalFields = [
  {
    name: 'Information Technology',
    slug: 'information-technology',
    category: 'STEM',
    rawAliases: [
      'Information Technology',
      'IT',
      'Computing',
      'Computer Science',
      'Information Tech',
    ],
  },
  {
    name: 'Engineering',
    slug: 'engineering',
    category: 'STEM',
    rawAliases: ['Engineering'],
  },
  {
    name: 'Business & Finance',
    slug: 'business-finance',
    category: 'Business',
    rawAliases: [
      'Business',
      'Finance',
      'Business and Finance',
      'Business Adminstration', // Typo in source
      'Business Administration',
      'Business & Economics',
    ],
  },
  {
    name: 'Accounting',
    slug: 'accounting',
    category: 'Business',
    rawAliases: ['Accounting', 'Accounting & Finance'],
  },
  {
    name: 'Banking',
    slug: 'banking',
    category: 'Business',
    rawAliases: ['Banking'],
  },
  {
    name: 'Insurance',
    slug: 'insurance',
    category: 'Business',
    rawAliases: ['Insurance'],
  },
  {
    name: 'Social Sciences',
    slug: 'social-sciences',
    category: 'Social Sciences',
    rawAliases: ['Social Science', 'Social Sciences'],
  },
  {
    name: 'Applied Sciences',
    slug: 'applied-sciences',
    category: 'STEM',
    rawAliases: ['Applied Science', 'Applied Sciences'],
  },
  {
    name: 'Media & Communication',
    slug: 'media-communication',
    category: 'Arts',
    rawAliases: [
      'Media & Communication',
      'Media and Communication',
      'Communication',
      'Mass Communication',
    ],
  },
  {
    name: 'Education',
    slug: 'education',
    category: 'Education',
    rawAliases: ['Education', 'Educational Studies'],
  },
  {
    name: 'Chinese Studies',
    slug: 'chinese-studies',
    category: 'Humanities',
    rawAliases: ['Chinese Studies'],
  },
  {
    name: 'Counseling',
    slug: 'counseling',
    category: 'Social Sciences',
    rawAliases: ['Couseling', 'Counseling'], // Typo in source
  },
  {
    name: 'Multimedia',
    slug: 'multimedia',
    category: 'Arts',
    rawAliases: ['Multimedia'],
  },
  {
    name: 'Humanities',
    slug: 'humanities',
    category: 'Humanities',
    rawAliases: ['Humanities'],
  },
  {
    name: 'Islamic Studies',
    slug: 'islamic-studies',
    category: 'Humanities',
    rawAliases: [
      'Islamic General',
      'Islamic Science',
      "Da'wah & Islamic Management",
      'Quranic and Sunnah Studies',
      'Islamic Reveal Knowledge & Human Science',
    ],
  },
  {
    name: 'Language Studies',
    slug: 'language-studies',
    category: 'Humanities',
    rawAliases: ['Language Studies', 'Arabic Studies'],
  },
  {
    name: 'Art & Design',
    slug: 'art-design',
    category: 'Arts',
    rawAliases: ['Art & Design', 'Design', 'Interior Design', 'Fashion'],
  },
  {
    name: 'Psychology',
    slug: 'psychology',
    category: 'Social Sciences',
    rawAliases: ['Psychology'],
  },
  {
    name: 'Tourism & Hospitality',
    slug: 'tourism-hospitality',
    category: 'Services',
    rawAliases: [
      'Tourism & Hospitality',
      'Hospitality & Tourism Management',
      'Hospitality',
      'Tourism & Events',
      'Tourism',
      'Culinary',
    ],
  },
  {
    name: 'Computer Management',
    slug: 'computer-management',
    category: 'STEM',
    rawAliases: ['Computer Management'],
  },
  {
    name: 'Mathematical Sciences',
    slug: 'mathematical-sciences',
    category: 'STEM',
    rawAliases: ['Mathematical Science', 'Mathematical Sciences', 'Data & Mathematics'],
  },
  {
    name: 'Orthodontics',
    slug: 'orthodontics',
    category: 'Health',
    rawAliases: ['Orthodontics'],
  },
  {
    name: 'Economics',
    slug: 'economics',
    category: 'Business',
    rawAliases: ['Economics', 'Economics and Muamalat Administration'],
  },
  {
    name: 'Built Environment & Architecture',
    slug: 'built-environment-architecture',
    category: 'STEM',
    rawAliases: [
      'Built Environment',
      'Architecture',
      'Build Environment & Architecture',
      'Quantity Surveying',
    ],
  },
  {
    name: 'Human Resources',
    slug: 'human-resources',
    category: 'Business',
    rawAliases: ['Human Resource'],
  },
  {
    name: 'Law',
    slug: 'law',
    category: 'Social Sciences',
    rawAliases: ['Law'],
  },
  {
    name: 'Technology Management',
    slug: 'technology-management',
    category: 'Business',
    rawAliases: ['Technology Management', 'Technology Management and Technopreneurship'],
  },
  {
    name: 'Technical & Vocational',
    slug: 'technical-vocational',
    category: 'STEM',
    rawAliases: ['Technical and Vocational'],
  },
  {
    name: 'Animation',
    slug: 'animation',
    category: 'Arts',
    rawAliases: ['Animation', 'Games and Animation'],
  },
  {
    name: 'Biotechnology',
    slug: 'biotechnology',
    category: 'STEM',
    rawAliases: ['Biotechnology'],
  },
  {
    name: 'Physiotherapy',
    slug: 'physiotherapy',
    category: 'Health',
    rawAliases: ['Physiotherapy'],
  },
  {
    name: 'Traditional Chinese Medicine',
    slug: 'traditional-chinese-medicine',
    category: 'Health',
    rawAliases: ['Traditional Chinese Medicine'],
  },
  {
    name: 'Earth & Marine Science',
    slug: 'earth-marine-science',
    category: 'STEM',
    rawAliases: ['Earth & Marine Science'],
  },
  {
    name: 'Physical Science',
    slug: 'physical-science',
    category: 'STEM',
    rawAliases: ['Physical Science'],
  },
  {
    name: 'Environment',
    slug: 'environment',
    category: 'STEM',
    rawAliases: ['Environment', 'Forestry & Environment'],
  },
  {
    name: 'Maritime Studies',
    slug: 'maritime-studies',
    category: 'STEM',
    rawAliases: ['Maritime Studies'],
  },
  {
    name: 'Fisheries & Food Science',
    slug: 'fisheries-food-science',
    category: 'STEM',
    rawAliases: ['Fisheries & Food Science', 'Food Science'],
  },
  {
    name: 'Health Sciences',
    slug: 'health-sciences',
    category: 'Health',
    rawAliases: [
      'Health Sciences',
      'Health',
      'Medicine & Health Science',
      'Medical & Life Sciences',
      'Medicine & Defences Health',
    ],
  },
  {
    name: 'Medicine',
    slug: 'medicine',
    category: 'Health',
    rawAliases: ['Medicine'],
  },
  {
    name: 'Pharmacy',
    slug: 'pharmacy',
    category: 'Health',
    rawAliases: ['Pharmacy'],
  },
  {
    name: 'Dentistry',
    slug: 'dentistry',
    category: 'Health',
    rawAliases: ['Dentistry'],
  },
  {
    name: 'Nursing',
    slug: 'nursing',
    category: 'Health',
    rawAliases: ['Nursing'],
  },
  {
    name: 'Science',
    slug: 'science',
    category: 'STEM',
    rawAliases: ['Science', 'Sciences', 'Biosciences', 'Science & Technology'],
  },
  {
    name: 'Agriculture',
    slug: 'agriculture',
    category: 'STEM',
    rawAliases: ['Agriculture'],
  },
  {
    name: 'Modern Language',
    slug: 'modern-language',
    category: 'Humanities',
    rawAliases: ['Modern Language & Communication'],
  },
  {
    name: 'Human Ecology',
    slug: 'human-ecology',
    category: 'Social Sciences',
    rawAliases: ['Human Ecology'],
  },
  {
    name: 'Liberal Arts & Sciences',
    slug: 'liberal-arts-sciences',
    category: 'Humanities',
    rawAliases: ['Liberal Arts & Sciences'],
  },
  {
    name: 'American Education',
    slug: 'american-education',
    category: 'Education',
    rawAliases: ['American Education'],
  },
  {
    name: 'Arts',
    slug: 'arts',
    category: 'Arts',
    rawAliases: ['Arts', 'Arts & Social Sciences'],
  },
  {
    name: 'Applied Innovation',
    slug: 'applied-innovation',
    category: 'STEM',
    rawAliases: ['Applied Innovation'],
  },
  {
    name: 'Aviation',
    slug: 'aviation',
    category: 'STEM',
    rawAliases: ['Aviation'],
  },
  {
    name: 'Film & Television',
    slug: 'film-television',
    category: 'Arts',
    rawAliases: ['Film and Television'],
  },
  {
    name: 'Management & Marketing',
    slug: 'management-marketing',
    category: 'Business',
    rawAliases: ['Management & Marketing', 'Studies & Management', 'Strategy & Business'],
  },
  {
    name: 'Semiconductor',
    slug: 'semiconductor',
    category: 'STEM',
    rawAliases: ['Semiconductor'],
  },
  {
    name: 'All Fields',
    slug: 'all-fields',
    category: null,
    rawAliases: ['All'],
  },
] as const

export type CanonicalField = (typeof canonicalFields)[number]
